app/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('',views.add_details,name='add_details'),
    path('charts/',views.show_charts, name="charts")
]

placementpole/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls'))
]

app/models.py
from django.db import models
from django import forms

# Create your models here.
YEAR = (
        ('2023', '2023'),
        ('2022', '2022'),
    )
BRANCH = (
        ('ECE', 'ECE'),
        ('CSE(select-for-similar-brances-like-csm-Ai-IT)', 'CSE(select-for-similar-brances-like-csm-Ai-IT)'),
        ('MECH','MECH'),
        ('CIVIL','CIVIL'),
        ('CHEM','CHEM'),
        ('EEE','EEE'),
    )
PACKAGE = (
    ('2-6','2-6'),
    ('7-12','7-12'),
    ('13-18','13-18'),
    ('19-24','19-24'),
    ('more','more')
)
PLACEDON={
    ('core','core'),
    ('IT(software)','IT(software)')
}
class Details(models.Model):
    year = models.CharField(max_length=50, choices=YEAR)
    branch = models.CharField(max_length=50, choices=BRANCH)
    placed = models.BooleanField(default=False)
    placed_on = models.CharField(max_length=50,choices=PLACEDON,blank=True)
    package = models.CharField(max_length=50, choices=PACKAGE, blank=True)
    

class Years(models.Model):
    year = models.CharField(max_length=50, choices=YEAR)

app/forms.py
from django import forms
from .models import Details, Years

class DetailsForm(forms.ModelForm):
    class Meta:
        model = Details
        fields = ('year', 'branch', 'placed', 'placed_on', 'package')

    def __init__(self, *args, **kwargs):
        super(DetailsForm, self).__init__(*args, **kwargs)
        # Add custom labels for fields
        self.fields['year'].label = 'Year of Passing'
        self.fields['branch'].label = 'Branch of Study'
        self.fields['placed'].label = 'Placed in Campus Recruitment?'
        self.fields['placed_on'].label = 'Name of Company Placed With'
        self.fields['package'].label = 'Placement Package (in Lakhs per Annum)'

        # Add custom help text for fields
        self.fields['placed'].help_text = 'Select "Yes" if you were placed in a campus recruitment drive.'
        self.fields['placed_on'].help_text = 'Enter the name of the company you were placed with, if applicable.'
        self.fields['package'].help_text = 'Enter the package you were offered in lakhs per annum, if applicable.'


class yearForm(forms.ModelForm):
    class Meta:
        model = Years
        fields = ('year',)
    
    def __init__ (self, *args, **kwargs):
        super(yearForm, self).__init__(*args, **kwargs)
        self.fields['year'].label = 'Select Year'

app/views.py
from django.shortcuts import render, redirect
from .forms import DetailsForm, yearForm
from .models import Details
from django.db.models import Count
from django.db.models import Q
import math

def add_details(request):
    if request.method == 'POST':
        form = DetailsForm(request.POST)

        if form.is_valid():
            # Save the form data to the database
            form.save()
            # Redirect to a success page
            return redirect('/')
    else:
        # Show a blank form
        form = DetailsForm()

    return render(request, 'add_details.html', {'form': form})


def show_charts(request):
    global year
    if request.method == 'POST':
        yform = yearForm(request.POST)
        year = yform['year'].value()
    else:
        yform = yearForm()
        year = 2023

    tcount = len(Details.objects.filter(year=year).values())

    #placed / not placed info
    placed_ct = len(Details.objects.filter(year=year, placed = True).values())
    not_placed_ct = len(Details.objects.filter(year=year, placed = False).values())
    
    placed_pt = calcPerc(placed_ct, placed_ct+not_placed_ct)
    not_placed_pt = calcPerc(not_placed_ct, placed_ct+not_placed_ct)

    #core / it info
    core_ct = len(Details.objects.filter(year=year, placed_on = "core").values())
    it_ct = len(Details.objects.filter(year=year, placed_on = "IT(software)").values())
    
    core_pt = calcPerc(core_ct, core_ct+it_ct)
    it_pt = calcPerc(it_ct, core_ct+it_ct)

    #salary
    l26 = len(Details.objects.filter(year=year, package = "2-6").values())
    l612 = len(Details.objects.filter(year=year, package ="7-12").values())
    l128 = len(Details.objects.filter(year=year, package = "13-18").values())
    l184 = len(Details.objects.filter(year=year, package ="19-24").values())
    l24 = len(Details.objects.filter(year=year, package ="more").values())
    salTotal = l26+l128+l184+l612+l24

    l26pt = calcPerc(l26, salTotal)
    l612pt = calcPerc(l612, salTotal) + l26pt
    l128pt = calcPerc(l128, salTotal) + l612pt
    l184pt = calcPerc(l184, salTotal) + l128pt
    l24pt = calcPerc(l24, salTotal) + l184pt

    sdata = {
        "l26":l26, "l26pt":l26pt,
        "l612":l612, "l612pt": l612pt,
        "l128":l128, "l128pt": l128pt,
        "l184": l184, "l184pt": l184pt,
        "l24":l24, "l24pt":l24pt
    }

    data = {"pc":placed_ct, "npc":not_placed_ct, "pt": placed_pt, "npt":not_placed_pt, "tot":tcount, "cc":core_ct, "ic":it_ct, "ct": core_pt, "it": it_pt}

    return render(request, 'charts.html', {"data":data, "sdata": sdata, "form":yform})

def calcPerc (v, tot):
    return math.floor((((v/tot)*100)/100)*360)

app/templates/add_details.html
<!DOCTYPE html>
<html>

<head>
	<title>Student Data Form</title>
	<style>
		@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap');

		body {
			font-family: "Poppins";
			background-color: #f2f2f2;
		}

		h1 {
			text-align: center;
			margin-top: 50px;
			color: #333;
		}

		form {
			max-width: 500px;
			margin: 0 auto;
			background-color: #fff;
			padding: 20px;
			border-radius: 5px;
			box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
		}

		input[type="text"],
		select {
			width: 100%;
			padding: 12px 20px;
			margin: 8px 0;
			display: inline-block;
			border: 1px solid #ccc;
			border-radius: 4px;
			box-sizing: border-box;
		}

		input[type="submit"] {
			background-color: #4CAF50;
			color: white;
			padding: 12px 20px;
			margin-top: 20px;
			border: none;
			border-radius: 4px;
			cursor: pointer;
		}

		input[type="submit"]:hover {
			background-color: #45a049;
		}

		.btn {
			width: max-content;
			height: max-content;
			outline: none;
			border: none;
			background-color: #333;
			color: #fff;
			font-size: 13px;
			font-family: "Poppins";
			padding: 10px 20px;
			margin-top: 15px;
			margin-right: 10px;
			text-decoration: none;
			border-radius: 5px;
			cursor: pointer;
		}
	</style>
</head>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<body>
	<h1>Add Details</h1>
	<!-- placement.html -->
	<form method="post" action="{% url 'add_details' %}">
		{% csrf_token %}
		{% if form.errors %}
		<ul>
			{% for field in form %}
			{% for error in field.errors %}
			<li>{{ field.label }}: {{ error }}</li>
			{% endfor %}
			{% endfor %}
		</ul>
		{% endif %}
		<div>
			<label for="{{ form.year.id_for_label }}">Year:</label>
			{{ form.year }}
		</div>
		<div>
			<label for="{{ form.branch.id_for_label }}">Branch:</label>
			{{ form.branch }}
		</div>
		<div>
			<label for="{{ form.placed.id_for_label }}">Placed:</label>
			{{ form.placed }}
		</div>
		<div>
			<label for="{{ form.placed_on.id_for_label }}">Placed_on:</label>
			{{ form.placed_on }}
		</div>
		<div>
			<label for="{{ form.package.id_for_label }}">Package:</label>
			{{ form.package }}
		</div>
		<div>
			<button class="btn" type="submit">Submit</button>
			<a class="btn" href="/charts/">View Analytics</a>
		</div>
	</form>

	<script>
		$(document).ready(function () {
			var placedField = $('#id_placed');
			var packageField = $('#id_package');
			var placed_onField = $('#id_placed_on');

			packageField.prop('disabled', !placedField.is(':checked'));
			placed_onField.prop('disabled', !placedField.is(':checked'));

			placedField.change(function () {
				packageField.prop('disabled', !$(this).is(':checked'));
				placed_onField.prop('disabled', !$(this).is(':checked'));
			});
		});
	</script>

</body>

</html>

app/templates/charts.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Placement Poll - Charts</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap');

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: "Poppins";
            user-select: none;
        }

        :root {
            --p: rgba(0, 0, 0, 0.8);
            --s: #6d6fff;
            --t: rgb(255, 46, 46);
            --f: #56ff40;
            --fv: #25ffbe;
        }

        .container {
            width: 100%;
            height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            position: relative;
        }

        .title {
            position: absolute;
            top: 30px;
            left: 50%;
            transform: translateX(-50%);
            font-size: 25px;
            font-weight: 700;
            height: 50px;
        }

        .charts-cont {
            gap: 80px;
            width: max-content;
            height: max-content;
            display: flex;
        }

        .chartCont {
            width: max-content;
            height: max-content;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }

        .chart {
            width: 300px;
            height: 300px;
            display: flex;
            justify-content: center;
            align-items: center;
            border-radius: 50%;
            font-family: "Poppins";
        }

        .inner {
            border-radius: 50%;
            width: 80%;
            height: 80%;
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
            font-size: 13.5px;
            gap: 5px;
            background-color: white;
        }

        .label {
            width: 400px;
            text-align: center;
            margin-bottom: 25px;
        }

        .colors {
            width: 100%;
            display: flex;
            justify-content: center;
            margin-top: 30px;
            align-items: center;
            gap: 30px;
        }

        .lab {
            font-size: 12px;
        }

        .c-cont {
            display: flex;
            align-items: center;
            gap: 10px;
        }

        .col {
            width: 15px;
            height: 15px;
            background-color: blue;
        }

        .p {
            background-color: var(--p);
        }

        .s {
            background-color: var(--s);
        }

        .t {
            background-color: var(--t);
        }

        .f {
            background-color: var(--f);
        }

        .fv {
            background-color: var(--fv);
        }

        .c2 {
            background-image: conic-gradient(var(--s) var(--a-start), var(--s) var(--a-end), var(--p) var(--b-start), var(--p) var(--b-end));
        }

        .c5 {
            background-image: conic-gradient(var(--p) var(--a-start), var(--p) var(--a-end), var(--s) var(--b-start), var(--s) var(--b-end), var(--t) var(--c-start), var(--t) var(--c-end), var(--f) var(--d-start), var(--f) var(--d-end), var(--fv) var(--e-start), var(--fv) var(--e-end));
        }

        .inpCont {
            width: max-content;
            height: max-content;
            display: flex;
            position: absolute;
            top: 90px;
            left: 50%;
            transform: translateX(-50%);
        }

        .lable {
            margin-right: 10px;
            font-family: "Poppins";
        }

        .btn {
            width: max-content;
            height: max-content;
            cursor: pointer;
            font-family: "Poppins";
            font-size: 14px;
            padding: 3px 10px;
            margin-left: 15px;
            background-color: #333;
            color: #fff;
            border: none;
            border-radius: 5px;
        }

        @media only screen and (max-width: 1384px) {
            .title {
                width: 85%;
                height: max-content;
                position: initial;
                text-align: center;
                transform: translate(0);
                margin-bottom: 20px;
            }

            .inpCont {
                transform: translate(0);
                position: initial;
            }

            .charts-cont {
                margin-top: 60px;
                flex-direction: column;
            }

            .container {
                height: max-content;
                padding: 40px 0;
                justify-content: flex-start;
            }
        }
    </style>
</head>

<body>
    <div class="container">
        <p class="title">Analysis on Students (total - {{data.tot}} students)</p>
        <form method="POST" action="{% url 'charts' %}" class="inpCont">
            {% csrf_token %}
            {% if form.errors %}
            <ul>
                {% for field in form %}
                {% for error in field.errors %}
                <li>{{ field.label }}: {{ error }}</li>
                {% endfor %}
                {% endfor %}
            </ul>
            {% endif %}
            <div>
                <label class="lable" for="{{ form.year.id_for_label }}">Year:</label>
                {{ form.year }}
            </div>
            <button class="btn" type="submit">View Data</button>
        </form>
        <div class="charts-cont">

            <div class="chartCont">
                <p class="label">Placed / Not Placed</p>
                <div class="chart c2"
                    style="--a-start:{{data.npt}}deg; --a-end:{{data.pt}}deg; --b-start:{{data.pt}}deg; --b-end:{{data.npt}}deg">
                    <div class="inner">
                        <p class="ilab">Placed : {{data.pc}} students</p>
                        <p class="ilab">Not Placed : {{data.npc}} students</p>
                    </div>
                </div>
                <div class="colors">
                    <div class="c-cont">
                        <div class="col s"></div>
                        <p class="lab">Placed</p>
                    </div>
                    <div class="c-cont">
                        <div class="col p"></div>
                        <p class="lab">Not Placed</p>
                    </div>
                </div>
            </div>

            <div class="chartCont">
                <p class="label">Core / It Software (Placed)</p>
                <div class="chart c2"
                    style="--a-start:{{data.it}}deg; --a-end:{{data.ct}}deg; --b-start:{{data.ct}}deg; --b-end:{{data.it}}deg">
                    <div class="inner">
                        <p class="ilab">Core : {{data.cc}} students</p>
                        <p class="ilab">It Software : {{data.ic}} students</p>
                    </div>
                </div>
                <div class="colors">
                    <div class="c-cont">
                        <div class="col s"></div>
                        <p class="lab">Core</p>
                    </div>
                    <div class="c-cont">
                        <div class="col p"></div>
                        <p class=" lab">IT(Software)</p>
                    </div>
                </div>
            </div>

            <div class="chartCont">
                <p class="label">Salary (Placed)</p>
                <div class="chart c5"
                    style="--a-start:0deg; --a-end:{{sdata.l26pt}}deg; --b-start:{{sdata.l26pt}}deg; --b-end:{{sdata.l612pt}}deg; --c-start:{{sdata.l612pt}}deg; --c-end:{{sdata.l128pt}}deg; --d-start:{{sdata.l128pt}}deg; --d-end:{{sdata.l184pt}}deg; --e-start:{{sdata.l184pt}}deg; --e-end:360deg;">
                    <div class="inner">
                        <p class="ilab">2-6 : {{sdata.l26}} students</p>
                        <p class="ilab">7-12 : {{sdata.l612}} students</p>
                        <p class="ilab">13-18 : {{sdata.l128}} students</p>
                        <p class="ilab">19-24 : {{sdata.l184}} students</p>
                        <p class="ilab">24+ : {{sdata.l24}} students</p>
                    </div>
                </div>
                <div class="colors">
                    <div class="c-cont">
                        <div class="col p"></div>
                        <p class="lab">2-6</p>
                    </div>
                    <div class="c-cont">
                        <div class="col s"></div>
                        <p class="lab">7-12</p>
                    </div>
                    <div class="c-cont">
                        <div class="col t"></div>
                        <p class="lab">13-18</p>
                    </div>
                    <div class="c-cont">
                        <div class="col f"></div>
                        <p class="lab">19-24</p>
                    </div>
                    <div class="c-cont">
                        <div class="col fv"></div>
                        <p class="lab">24+</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

</html>